### PR TITLE
feat: decode state and piece count values from Sencon

### PR DESCRIPTION
**Pull request by tukusejssirs**

### CODE REVIEW

**Comment by tukusejssirs** [comment]
I am not quite sure if this PR fixes #177. I think this PR is a part of a new feature.

Tell me if I’m wrong. :pray:

**Comment by tukusejssirs** [comment]
Maybe we should wait woth merging the PR until we finish adding the entire feature (Sencon device).

**Review by bburns — APPROVED** [review]
Thanks Otto!

**Comment by bburns** [comment]
Yeah this is half of #177 - i'll add be/le handling

**Pull request merged**
